development:
  adapter: postgis
  template: template0
  encoding: utf-8
  database: wicd
  username: <%= ENV['DB_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASS'] || '' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  host: localhost
  postgis_extension: true
  schema_search_path: "public,postgis"

staging:
  adapter: postgis
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  postgis_extension: postgis
  schema_search_path: public,postgis

production:
  adapter: postgis
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  postgis_extension: postgis
  schema_search_path: public,postgis
